# Generated by Django 2.2 on 2019-07-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
